ALTER TABLE estimates ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS zip TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS quoted_price NUMERIC DEFAULT 0;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS visit_date DATE;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'quoted';
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS client_id INTEGER;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS record_type TEXT DEFAULT 'lead';
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS source_lead_id INTEGER;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS converted_client_id INTEGER;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS converted_job_id INTEGER;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS converted_at TIMESTAMP;

ALTER TABLE estimates ALTER COLUMN client_id DROP NOT NULL;

UPDATE estimates SET record_type = 'lead' WHERE record_type IS NULL OR record_type = '';
