ALTER TABLE companies
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE companies
ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

ALTER TABLE companies
ADD COLUMN IF NOT EXISTS verification_notes TEXT;
